### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by incpi** [incpi/Dark-CPI-Web-Extension#1]
Hello,

It's displayed as a Light theme
- Mapping functions are not displayed properly
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/87596092/e76f2174-d648-4799-be3e-c167e8c8fe45)

**Comment by incpi** [comment]
fixed #1 in [Dev](https://github.com/incpi/Dark-CPI-Web-Extension/tree/Dev)

**Comment by DevGregor** [comment]
Here seems to be an issue as well
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/77123831/81eb62b8-e91b-435a-9da4-ce9f4cf9a0a1)

**Comment by incpi** [comment]
Thankyou

Noted, 
Will be fixed in the next version. V 1.2 dev

If you find it anymore issue. Let me know
Omkar
