### ISSUE TITLE
the part that turns off the screen in trace mode

### ISSUE THREAD

**Issue by IKSAPGitHub** [incpi/Dark-CPI-Web-Extension#15]
**Describe the bug**
when I enter trace mode I can't see the screen completely, something is blocking the screen. attached is the pic

**To Reproduce**
1. Go to trace mode

**Version**
3.13.1 on chrome

**Environment**
multi environment

**Expected behavior**
entering trace mode

**Screenshots**
![image](https://github.com/user-attachments/assets/c6601a0c-0f8f-4b81-9448-91ef0d8cec9e)

**Desktop (please complete the following information):**
 - OS: win 11 pro 64 bit
 - Browser chrome

**Comment by incpi** [comment]
Hello @IKSAPGitHub  

Noted! the half screen issue has been resolved and will be included in the next release. 

Thank you so much.
Omkar.

**Comment by IKSAPGitHub** [comment]
Hello,

Thanks for the fix, it worked!

Thanks for your efforts.
