### ISSUE TITLE
Text coloring messes with SAP CPI Helper

### ISSUE THREAD

**Issue by DevGregor** [incpi/Dark-CPI-Web-Extension#5]
**Describe the bug**
If you have both CPI Helper (4.0.0) and Dark CPI installed, Dark CPI seems to overwrite some text coloring of the CPI Helper.

**To Reproduce**
1. Install both CPI Helper (4.0.0) and Dark CPI
2. Check What's New Popup

**Expected behavior**
Some texts and headers are almost not visible unless Dark CPI is turned off.

**Screenshots**
Without Addon:
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/77123831/2d112141-1d4d-40aa-9c31-1a24da17f561)
With Addon:
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/77123831/2cd9672f-492d-4739-a856-9e5d3ab78bca)

Without Addon:
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/77123831/a3c6bacc-13d9-4ad7-9ad0-2fe30bbb8c75)
With Addon:
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/77123831/f8c6cb2b-10a1-4f97-b65d-b7a415908620)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 125.0.6422.113

**Additional context**
Parts of this issue seem to be related to CPI Helper itself. Will make an issue there as well:
https://github.com/dbeck121/CPI-Helper-Chrome-Extension/issues/178

**Comment by incpi** [comment]
Hello @DevGregor,

This has to fixed in CPI helper. So, no fix for this extension. 
Thanks, Omkar

**Comment by DevGregor** [comment]
Hello @incpi 

Are you sure? Because some coloring issues in the CPI Helper soley happen by activating this addon. As shown by the screenshots in my first message, these coloring issues are only appearing when activating this addon alongside the CPI Helper. The others where it seems to be CPI Hepler related are posted there.

**Comment by incpi** [comment]
Hi @DevGregor,

Would you mind tell me which theme you are utilizing at the time of snapshot.
Case 1: morning horizon (default theme) or quartz theme, you won't have this issue.
I couldn't re-produce what you mentioned with light theme.
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/87596092/3d0cf2a9-6c28-4250-9a4c-980ba101d7a8)
![image](https://github.com/incpi/Dark-CPI-Web-Extension/assets/87596092/a103f43d-1042-45b6-9531-2bd338443c66)

Case 2: Dark Evening horizon theme. Yes, it has issues with CPI helper. CPI helper lacks in terms of dark theme support.

Yes, I am 100% certain that it has to Fix in Helper. You can also check CSS file in this tool as well.
Hope this helps.

**Comment by DevGregor** [comment]
> Hi @DevGregor,
> 
> Would you mind tell me which theme you are utilizing at the time of snapshot. Dark right. Let's Discuss,
> 
> Case 1: morning horizon (default theme) or quartz theme, you won't have this issue. I couldn't re-produce what you mentioned with light theme. ![image](https://private-user-images.githubusercontent.com/87596092/334080500-3d0cf2a9-6c28-4250-9a4c-980ba101d7a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDk0MTQsIm5iZiI6MTcxNjgwOTExNCwicGF0aCI6Ii84NzU5NjA5Mi8zMzQwODA1MDAtM2QwY2YyYTktNmMyOC00MjUwLTlhNGMtOTgwYmExMDFkN2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExMjUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYjdmOWMxMjI2MmJmOGEwYzc0ZTY4YjFlNThiODNlMWYyNzEwZjM5YTNjMGI3ZWQ0MzRlNmVlMjlhMjQzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoYBhgl4jU_5SdKTnEWCnHFnH_eS4k4hZpBPe4k6nDM) ![image](https://private-user-images.githubusercontent.com/87596092/334080603-a103f43d-1042-45b6-9531-2bd338443c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDk0MTQsIm5iZiI6MTcxNjgwOTExNCwicGF0aCI6Ii84NzU5NjA5Mi8zMzQwODA2MDMtYTEwM2Y0M2QtMTA0Mi00NWI2LTk1MzEtMmJkMzM4NDQzYzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExMjUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNmU2M2Y2MmM3Y2VhMmU1ZGQ4MmM0NGNlOTI4NzE3MjIzYmExNzVkN2JkZDYxMWM2ZWJjMmNlNWZmZjMwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fjqm2v7bdNKV3-prudiw7cYUb7huc4e2XuqgVO1hmXw)
> 
> Case 2: Dark Evening horizon theme. Yes, it has issues with CPI helper. CPI helper lacks in terms of dark theme support.
> 
> Yes, I am 100% certain that it has to Fix in Helper. You can also check CSS file in this tool as well. Hope this helps.

Okay, then I will close this here. Maybe from testing it has stored white color and sets it as background.
